# Versão do compose 
version: '3.8'
# Criação do volume
volumes:
  postgres_vol:

# Criação da network
networks:
  postgres_net:
    driver: bridge

# containers (services) que farão parte da Stack
services:
  #container postgres
  postgres:
    image: postgres:15
    hostname: postgres
    networks:
      - postgres_net
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    # ports:
    #  - 5432:5432

  # container pgadmin
  pgadmin:
    image: dpage/pgadmin4:6.20
    depends_on:
      - postgres
    networks:
      - postgres_net
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - 80:80

  # container API
  api:
    image: matdavgue/kube_news:V1
    # Build da imagem utilizando o Dockerfile contruído no momento que executa o Doker-compose up
    build:
      dockerfile: ./Dockerfile
      context: ./src
    environment:
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    networks:
      - postgres_net
    depends_on:
      - postgres
    ports:
      - 8080:8080
    