# Versão do compose 
version: '3.8'
# Criação do volume
volumes:
  mongodb_vol:

# Criação da network
networks:
  mongodb_net:
    driver: bridge

# containers (services) que farão parte da Stack
services:
  #container mongodb
  mongodb:
    image: mongo:4.4.3
    # ports:
    #   - 27017:27017
    networks:
      - mongodb_net
    volumes:
      - mongodb_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD_MONGO}
    
  # container Mongo Express
  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    networks:
      - mongodb_net
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${USERNAME_EXPRESS}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PASSWORD_EXPRESS}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME_MONGO}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD_MONGO}
    ports:
      - 8083:8081 #Antivirus local estava usando a porta 8081