apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx
spec:
  selector:
    matchLabels:
      app: myapp-nginx
  template:
    metadata:
      labels:
        app: myapp-nginx
    spec:
      initContainer:
        - name: init
          image: kubedevio/ubuntu-curl:v1
          command:
                - "curl"
                - "-x"
                - "POST"
                - "http://pruu.herokuapp.com/dump/initContainer"
      containers:
      - name: myapp-nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command:
                - "curl"
                - "-x"
                - "POST"
                - "http://pruu.herokuapp.com/dump/lifecyclestart"
          preStop:
            exec:
              command:
                - "curl"
                - "-x"
                - "POST"
                - "http://pruu.herokuapp.com/dump/lifecyclestop"
        resources:
          limits:
            memory: "32Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
