# Manisfesto para criação de um pod de forma declarativa

# Representa o agrupamento da API do objeto que será criado
# Executa kubectl api-resources para descobrir a versão
apiVersion: apps/v1

# É o tipo de objeto que será criado
kind: Deployment

# Metadata do deployment, atributos, nomes e informações sobre o replicaset
metadata:
  name: teste-deployment

# Especificação do deployment
spec:
  # ajuste de replicas par escalabilidade
  replicas: 25
  selector:
    matchLabels:
      app: exemplo
  # especificação do pod para o deployment
  template:
    metadata:
      # match com labels
      labels:
        app: exemplo
    # especificação do pod
    spec:
      containers:
        - name: meucontainer
          image: kubedevio/nginx-color:green
  