apiVersion: v1
kind: Service
metadata:
  name: app-services
spec:
  selector:
    # selector/labels do deployment.yaml. Pega todos os pods com label exemplo
    app: exemplo
  ports:
    #TCP é o padrão
  - port: 80
    targetPort: 8080
  type: LoadBalancer
