apiVersion: v1
kind: LimitRange
metadata:
  name: limite-container
spec:
  limits:
    # Maximo aceitado
    - max:
        cpu: "800m"
        memory: "900Mi"
      # Mínimo aceitado
      min:
        cpu: 150m
        memory: 99Mi
      # Definição limites padrão caso o pod não tenha no monifesto o resource configurado
      default:
        cpu: "250m"
        memory: "128Mi"
      # Definições de recursos garantidos para rodar a aplicação caso no monifesto o requests não esteja configurado
      defaultRequest:
        cpu: "150m"
        memory: "100Mi"
      #type: Pod -> Para controlar o pod inteiro, abrangindo todos os container que estão no pod
      #type: PersistentVolumeClaim -> Para controlar volumes
      type: Container # controle indivibual para cada container dentro do pod
      
