apiVersion: v1
kind: Service
metadata:
  name: app-services
spec:
  selector:
    # selector/labels do deployment.yaml. Pega todos os pods com label exemplo
    app: exemplo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    # Quando não definido o tipo o default é ClusterIP
  type: ClusterIP
